### PR TITLE
Added support for expanded state line spacing

### PR DESCRIPTION
**Pull request by giljulio**
https://github.com/opacapp/multiline-collapsingtoolbar/issues/29

### CODE REVIEW

**Comment by giljulio** [comment]
@raphaelm @johan12345 what do you think?

**Comment by raphaelm** [comment]
Hi! :) Thanks for your pull request! I believe this is an useful addition. It is naturally no part of the original collapsing toolbar, but it makes sense for our version. @johan12345, do you agree?
I haven't tested it yet, though.

**Comment by johan12345** [comment]
Looks good to me :)

**Comment by raphaelm** [comment]
Thanks for your contribution! :sparkles:

**Pull request merged**
